---

- name: Show Commands Playbook
  hosts: csr
  gather_facts: no
  connection: local

  tasks:
  - name: Get Login credentials
    include_vars: /mnt/hgfs/vm_shared/ansible/access.yml

  - name: Define Provider
    set_fact:
      provider:
        host: "{{ access['device_ip'] }}"
        username: "{{ access['username'] }}"
        password: "{{ access['password'] }}"

  - name: Run 'show output'
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
      # "CLI" is the variable for any show command on the $prompt
        - "{{ cli }}"

      
    register: output

  - debug: var=output.stdout_lines


...
